### ISSUE TITLE
Is it necessary to put `roxytest` in `Imports` (`Suggests` won't do)?

### ISSUE THREAD

**Issue by rorynolan** [mikldk/roxytest#1]
Hi there,
I love the package but am reluctant to grow the necessary dependencies of my packages (`Imports`). Is it possible to just put `roxytest` in `Suggests`, or could it be modified to allow this?
Thanks and keep up the great work,
Rory

**Comment by mikldk** [comment]
Yes, thanks! There is no need to import it. Thanks to @rubak . Please let me know if it is more clear now?

**Comment by mikldk** [comment]
Hopefully this is now solved and I close this. If you have any questions or comments, please feel free to reopen!

**Comment by rorynolan** [comment]
This is great, thanks for this!
