### ISSUE TITLE
Can only upate the timestamp for modified content?

### ISSUE THREAD

**Issue by ShixiangWang** [mikldk/roxytest#14]
I do love this package to auto-update the tests. However, I find it is annoying that all my tests have their timestamps updated in every commit, e.g. https://github.com/ShixiangWang/sigminer/commit/6a667374d4baea6cd2f36eee7e33e45a2f05af52

Is it possible to track the file modification and update the timestamp properly?

Best,
Shixiang

**Comment by mikldk** [comment]
Good point. Thanks! I think I will simply delete the "Last updated" line.

**Comment by mikldk** [comment]
This should be fixed by  a12e9a7.

**Comment by ShixiangWang** [comment]
@mikldk Thanks:)
