### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by mikldk** [mikldk/roxytest#15]
I am preparing a vignette and then I plan to submit to CRAN. Any objections, @rubak?

**Comment by rubak** [comment]
Sounds great. I'm happy to read the vignette before submission.

**Comment by mikldk** [comment]
@rubak : Can you please take a look at <https://mikldk.github.io/roxytest/index.html> - including the frontpage README as well as the vignette (and the docs in general). Feel free to edit as you see fit.

**Comment by rubak** [comment]
I edited a bit and also did some work to activate `tinytest` in <https://github.com/mikldk/roxytestdemo/> so maybe you could have a quick look at that at some point.

**Comment by mikldk** [comment]
Thanks.

**Comment by mikldk** [comment]
Note that you edited `README.md` instead of `README.Rmd` - I merged your changes into `README.Rmd`.

**Comment by rubak** [comment]
Do'h! I was reading online at GitHub and spotted something I wanted to change and just did a quick edit directly in the browser, so I completely forgot about the real source being Rmd...

**Comment by mikldk** [comment]
Fixed by 270b7a92c2e805837bd3a1b9dc6b73c6030b5a49. <https://cran.r-project.org/package=roxytest>
