### ISSUE TITLE
Run pkgdown with GitHub Actions

### ISSUE THREAD

**Issue by rubak** [mikldk/roxytest#16]
Could we borrow [this action workflow](https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml) to run pkgdown automatically?

**Comment by mikldk** [comment]
Added in 76565feb2da9f0c728f5b48797fba03a1abe52d7.

**Comment by mikldk** [comment]
The action runs, but it does not seem to update the site.

**Comment by rubak** [comment]
I think the default of this action is to deploy to the `gh-pages` branch but maybe you setup the site to look in `docs/` of `master` branch?

**Comment by mikldk** [comment]
Indeed! Thanks.
