### ISSUE TITLE
Use of context() with testthat

### ISSUE THREAD

**Issue by jl5000** [mikldk/roxytest#18]
It seems that the testthat tests which are generated use the context() function. I think this is no longer recommended: https://rdrr.io/cran/testthat/man/context.html

**Comment by mikldk** [comment]
Thanks for reporting. You are welcome to submit a PR (or else I will go ahead and fix it when I get to it).

**Comment by mikldk** [comment]
I am actually considering keeping it. Here, we ensure that filename and `context` is in sync, and `context` may be more informative as the filename is auto-generated. Do you have any input?

**Comment by jl5000** [comment]
It doesn't do any harm, it's just redundant as the information is captured in the test file name. There may come a point where it is removed from the package, but you don't have to worry about that for a long time yet. I don't have strong feelings about it.

**Comment by mikldk** [comment]
I think we will keep the `context()` for now, but I appreciate your suggestion - please continue if you have more :).
