### ISSUE TITLE
Roxytest Case Sensitive With File Extension

### ISSUE THREAD

**Issue by jrdnmdhl** [mikldk/roxytest#21]
There are no strictly followed standards in the R community for casing of R files, so in some cases these files will have lowercase ".r" and in other cases uppercase ".R". When roxytest writes test files, it simply takes the existing filename (including file extension) and adds a prefix. Because of this, the test files written by roxytest will follow whatever convention the user follows, which is arguably the correct behavior.

However, when roxytest handles cleanup, it currently uses a regex "^test-roxytest-.*\\.R$" that assumes a capitalized ".R". This means that users who's R files end in lowercase ".r" will not have their tests cleaned up by roxytest.

**Comment by jrdnmdhl** [comment]
See above PR for potential fix.

**Comment by mikldk** [comment]
Thanks, @jrdnmdhl - both for reporting and fixing the bug. Thanks!
