### ISSUE TITLE
testexamples Doesn't work well with Sinew

### ISSUE THREAD

**Issue by DataStrategist** [mikldk/roxytest#25]
Don't know if this behavior is the same as discussed in #12 , but here goes. Also this isn't a bug in your software per se, it's an incompatibility w/ another package that you may want to address.

I like [Sinew](https://github.com/yonicd/sinew) for creating the roxygen blocks (it has an addin, and does a lot of heavy lifting for you). Given the following:
```
a <- function(x,y="somethin"){
  boom = 1
  dplyr::mutate(iris, foo = "bar")
}
```

The default Sinew block looks like this right out of the gate:
```
#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param x PARAM_DESCRIPTION
#' @param y PARAM_DESCRIPTION, Default: 'somethin'
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples 
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @seealso 
#'  \code{\link[dplyr]{mutate}}
#' @rdname a
#' @export 
#' @importFrom dplyr mutate
a <- function(x,y="somethin"){
  boom = 1
  dplyr::mutate(iris, foo = "bar")
}
```

You can see the advantages almost immediately, it fills out parameters more richly, imports functions from packages, links things in `seealso` etc. The one thing that doesn't work w/ your `testexamples` is that the examples are wrapped in both a `\dontrun` AND an `if(interactive())`. Out of the box, examples placed here won't be picked up by testexamples. But when I remove the decorators and just have the example in @examples, it works fine.

Again... not a bug w/ your software, but just figured I'd park it here.

**Comment by mikldk** [comment]
@DataStrategist Thanks for starting this discussion. 

All in `\dontrun` is removed. So you need to write code necessary for tests outside this.

I am not sure I understand the problem with the current way it works. Can you provide an example with how it works now and how you think it should work?

**Comment by DataStrategist** [comment]
Yeah... that is 100% it. the /dontrun prevents the example from running, however If I'm explicitly using `testexample`, when I `roxygenize`, just because I don't want the examples to run doesn't mean I shouldn't test them. So my expectation was that these examples get copied over to the appropriate testthat file anywawy. But now we're in the weeds about specific behavior with these tags. What would be perfect would be a /dontrunbuttest tag, but we don't have one. Feel free to close.

**Comment by mikldk** [comment]
@DataStrategist Yes, fair enough. You need to copy the example code down to the `@tests` part.
